version: "3.7"
services:
  sql-server-db-container:
    container_name: sql-server-db-container
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "secret_p2ssw0rd"
